# Generated by Django 4.2.6 on 2024-05-25 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('concept1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aktor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_aktor', models.CharField(max_length=1024)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='concept1.project')),
            ],
        ),
        migrations.CreateModel(
            name='Ucase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_case', models.CharField(max_length=200)),
                ('aktor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ucase.aktor')),
            ],
        ),
        migrations.CreateModel(
            name='Spec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi', models.TextField()),
                ('flow', models.TextField()),
                ('goal', models.TextField()),
                ('awal', models.TextField()),
                ('akhir', models.TextField()),
                ('ucase', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ucase.ucase')),
            ],
        ),
        migrations.CreateModel(
            name='Skenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.TextField()),
                ('category', models.CharField(choices=[('N', 'Normal'), ('ALT', 'Alternative'), ('EXC', 'Exception')], default='N', max_length=3)),
                ('spec', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ucase.spec')),
            ],
        ),
    ]
