# Generated by Django 4.2.6 on 2024-05-25 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ucase', '0001_initial'),
        ('concept1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usecase',
            fields=[
                ('usecase_id', models.AutoField(primary_key=True, serialize=False)),
                ('usecase_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.CharField(blank=True, max_length=200)),
                ('desc', models.CharField(blank=True, max_length=200)),
                ('precon', models.CharField(blank=True, max_length=200)),
                ('precon_object', models.CharField(blank=True, max_length=200)),
                ('postcon', models.CharField(blank=True, max_length=200)),
                ('postcon_object', models.CharField(blank=True, max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concept1.project')),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucase.spec')),
                ('ucase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucase.ucase')),
            ],
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('step_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_alter', models.BooleanField()),
                ('subject', models.CharField(max_length=200)),
                ('activity', models.CharField(max_length=200)),
                ('object', models.CharField(max_length=200)),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usecasespectosequence.usecase')),
            ],
        ),
    ]
