# Generated by Django 4.2.6 on 2024-05-25 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usecasespectosequence', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usecase',
            name='spec',
        ),
    ]
