# Generated by Django 4.2.6 on 2024-05-25 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usecasespectosequence', '0002_remove_usecase_spec'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usecase',
            old_name='usecase_id',
            new_name='id',
        ),
    ]
