# Generated by Django 4.2.6 on 2024-05-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_project', models.CharField(max_length=100)),
                ('deskripsi_project', models.TextField()),
                ('img_path', models.TextField(max_length=455)),
            ],
        ),
    ]
